// ============================================================================
// Genetics V2 — Slice 13: rarity calibration simulation harness.
//
// Implements docs/GENETICS_GATE1_IMPLEMENTATION_CONTRACT.md §4.5.7 exactly —
// this file is the REAL (non-docs-only) successor to the Python simulation
// described in §4.5.5. It is a test-support module, not game runtime code:
// nothing under `overhaul/`, `ClassicApp.tsx`, `store.ts` or any UI component
// imports it, and it is excluded from the production bundle the same way any
// other unreferenced module is (tree-shaking, not a special case). It exists
// so `rarityCalibrationV2.test.ts` can exercise the REAL `breedV2` (Slice 4),
// the REAL `rarityOfV2` (Slice 3) and a REAL `mulberry32` RNG stream against a
// large, diverse, reproducible population — not a single fixed parent pair.
//
// Methodology (contract §4.5.7, fixed BEFORE any production constant in this
// package was touched by Slice 13 — see docs commit `docs(genetics): lock
// final Gate 1 calibration and regression`):
//
//   1. Population generation (burn-in, NOT part of the measured sample):
//      4000 base genomes, generated by weighted-random allele draw per locus
//      (ALLELE_OCCURRENCE_WEIGHTS_V2 below — the "occurrence weight" column
//      already documented in contract §4.2, encoded here for the first time
//      because nothing in game code needed it before this harness; weight-0
//      alleles, i.e. `aura_radiant`, the sole Gate 1 mutation-pool allele,
//      are excluded from the base draw pool — same rule contract §4.2 already
//      states for the docs-only simulation), split evenly species 1/species 2
//      by index parity (exactly 2000/2000 — deterministic, not a coin flip,
//      so "population contains species 1 and 2" is guaranteed, not merely
//      likely). Then three generations of 2000 intra-population breeds each
//      (random pairs drawn from the CURRENT population at that generation,
//      appended, never replacing — population grows 4000 -> 6000 -> 8000 ->
//      10000), using the REAL `breedV2` so later generations can carry
//      mutation-pool alleles (`aura_radiant`) exactly the way real players'
//      collections would after repeated breeding. None of these 6000 breed
//      results are counted toward the measured sample.
//   2. Measurement: exactly 100000 successful `breedV2` calls, each on a
//      freshly drawn random pair of two DISTINCT genomes from the final
//      10000-genome population (with replacement across draws — the pool
//      itself does not shrink, matching a stable collection being re-bred
//      many times). `pityCounter` is threaded as ONE continuous counter
//      across the ENTIRE run (burn-in AND measurement, one unbroken
//      sequence) — contract §4.5.7 point 2, matching the already-documented
//      §4.5.5 phrasing "непрерывный pityCounter через всю серию" applied
//      literally to the one RNG stream this harness drives from a single
//      seed. Species 1/2 pairs never fail `breedV2`'s species validation, so
//      every one of the 100000 draws is expected to succeed; the loop below
//      still defensively retries on a hypothetical failure rather than
//      assuming it, so "exactly 100000 successful results" is enforced by
//      construction, not by assumption.
//
// Byte-reproducible: one fixed numeric seed (RARITY_CALIBRATION_SEED) feeds
// one `mulberry32` stream for the whole run (population generation AND
// measurement) — no `Math.random`, no wall-clock, no Set/Map iteration order
// dependency (population is a plain array, indexed).
// ============================================================================

import type { AllelePair, GenomeV2, GenomeV2LocusKey } from './geneticsV2';
import { breedV2 } from './mutationV2';
import type { RarityTierV2 } from './rarityV2';
import { mulberry32 } from './rng';
import type { RngFn } from './rng';

/** Fixed seed for the whole calibration run — population generation and
 * measurement both derive from the ONE stream this produces. Changing this
 * value would change the exact measured counts; it is pinned here (not
 * re-derived per call) specifically so the test's assertion is reproducible
 * byte-for-byte across machines/runs, per the owner's explicit requirement. */
export const RARITY_CALIBRATION_SEED = 20260829;

/** Base population size (contract §4.5.7 point 1) — matches the docs-only
 * §4.5.5 simulation's own population size, carried over unchanged. */
const BASE_POPULATION_SIZE = 4000;
/** Three burn-in generations of 2000 intra-population breeds each. */
const BURN_IN_GENERATIONS = 3;
const BURN_IN_BREEDS_PER_GENERATION = 2000;
/** The measured sample size the owner specified — exactly 100000. */
export const RARITY_CALIBRATION_MEASURED_COUNT = 100_000;

function weightedPick<T extends string>(pool: readonly (readonly [T, number])[], rng: RngFn): T {
  const total = pool.reduce((sum, [, weight]) => sum + weight, 0);
  let draw = rng() * total;
  for (const [value, weight] of pool) {
    draw -= weight;
    if (draw < 0) return value;
  }
  // Floating-point edge case (draw lands exactly on the total) — last entry.
  return pool[pool.length - 1][0];
}

/**
 * Occurrence weight pools (contract §4.2 "Вес появления" column, transcribed
 * 1:1 — not invented for this harness). Weight-0 alleles are omitted from
 * each pool entirely (contract §4.2: weight 0 = "not in the birth pool,
 * reachable only through inheritance from an existing carrier or a mutation
 * roll") — `aura_radiant` is Gate 1's only such allele.
 */
const ALLELE_OCCURRENCE_WEIGHTS_V2 = {
  stemForm: [
    ['stem_standard', 64],
    ['stem_branching', 30],
    ['stem_climbing', 10],
  ],
  leafForm: [
    ['leaf_standard', 53],
    ['leaf_broad', 25],
    ['leaf_narrow', 17],
    ['leaf_frilled', 8],
  ],
  flowerForm: [
    ['flower_standard', 53],
    ['flower_fan', 25],
    ['flower_cap', 17],
    ['flower_star', 8],
  ],
  primaryColor: [
    ['primary_honey', 17],
    ['primary_amber', 19],
    ['primary_sunset', 21],
    ['primary_coral', 23],
    ['primary_lilac', 8],
    ['primary_violet', 10],
    ['primary_leaf', 5],
    ['primary_frost', 1],
  ],
  secondaryColor: [
    ['secondary_forest', 19],
    ['secondary_sunset', 21],
    ['secondary_amber', 23],
    ['secondary_crimson', 16],
    ['secondary_purple', 14],
    ['secondary_sky', 8],
    ['secondary_ochre', 2],
  ],
  leafColor: [
    ['leaf_color_meadow', 58],
    ['leaf_color_fresh', 30],
    ['leaf_color_forest', 15],
  ],
  pattern: [
    ['pattern_solid', 48],
    ['pattern_duotone', 30],
    ['pattern_spots', 14],
    ['pattern_stripes', 9],
    ['pattern_veins', 2],
  ],
  size: [
    ['size_normal', 53],
    ['size_large', 22],
    ['size_small', 20],
    ['size_giant', 8],
  ],
  aura: [
    ['aura_none', 58],
    ['aura_faint', 28],
    ['aura_glow', 15],
    // aura_radiant intentionally excluded — weight 0, mutation-pool only.
  ],
} as const satisfies Record<GenomeV2LocusKey, readonly (readonly [string, number])[]>;

function randomAllelePairV2<K extends GenomeV2LocusKey>(locus: K, rng: RngFn): AllelePair<string> {
  const pool = ALLELE_OCCURRENCE_WEIGHTS_V2[locus];
  return {
    a: weightedPick(pool, rng),
    b: weightedPick(pool, rng),
  };
}

/** One randomly generated base genome (contract §4.5.7 point 1) — every
 * locus drawn independently from its occurrence-weight pool, `mutationId`
 * always `null` (a base genome is not itself a mutation result). */
function generateBaseGenomeV2(speciesId: number, rng: RngFn): GenomeV2 {
  return {
    stemForm: randomAllelePairV2('stemForm', rng),
    leafForm: randomAllelePairV2('leafForm', rng),
    flowerForm: randomAllelePairV2('flowerForm', rng),
    primaryColor: randomAllelePairV2('primaryColor', rng),
    secondaryColor: randomAllelePairV2('secondaryColor', rng),
    leafColor: randomAllelePairV2('leafColor', rng),
    pattern: randomAllelePairV2('pattern', rng),
    size: randomAllelePairV2('size', rng),
    aura: randomAllelePairV2('aura', rng),
    speciesId,
    mutationId: null,
  } as GenomeV2;
}

/** Picks two DISTINCT random indices into `population` — retries on a
 * collision rather than allowing self-breeding, matching the real game's
 * `breedNurseryV2` `same_parent` guard (contract §4.8.7/§4.9.2). Bounded
 * retry: population size is always >= 4000, so collision probability per
 * draw is <= 1/4000 and an unbounded loop is not a realistic concern, but a
 * hard cap keeps this defensive rather than truly unbounded. */
function pickDistinctPairIndices(populationSize: number, rng: RngFn): [number, number] {
  const a = Math.floor(rng() * populationSize);
  for (let attempt = 0; attempt < 50; attempt++) {
    const b = Math.floor(rng() * populationSize);
    if (b !== a) return [a, b];
  }
  // Astronomically unlikely with populationSize >= 4000 — last resort.
  return [a, (a + 1) % populationSize];
}

export interface RarityCalibrationResult {
  readonly counts: Record<RarityTierV2, number>;
  readonly total: number;
  readonly populationSize: number;
  readonly finalPityCounter: number;
}

function emptyCounts(): Record<RarityTierV2, number> {
  return { Common: 0, Uncommon: 0, Rare: 0, Epic: 0, Legendary: 0, Mythic: 0 };
}

/**
 * Builds the representative burn-in population (contract §4.5.7 point 1) and
 * returns it together with the RNG/pity state at the moment burn-in ends, so
 * the caller can continue the SAME continuous pity counter into measurement
 * (contract §4.5.7 point 2 — "один непрерывный pityCounter через весь
 * прогон"). None of the burn-in breed results are inspected or counted —
 * only the resulting genomes matter, to grow population diversity (including
 * genomes that carry `aura_radiant` via real mutation, exactly like a real
 * player's collection would after repeated breeding).
 */
function buildRepresentativePopulationV2(rng: RngFn): { population: GenomeV2[]; pityCounter: number } {
  const population: GenomeV2[] = [];
  for (let i = 0; i < BASE_POPULATION_SIZE; i++) {
    // Even index -> species 1, odd index -> species 2: an exact 50/50 split,
    // not a probabilistic one, so "population contains species 1 and 2" is
    // guaranteed by construction (owner requirement), not a matter of luck.
    const speciesId = i % 2 === 0 ? 1 : 2;
    population.push(generateBaseGenomeV2(speciesId, rng));
  }

  let pityCounter = 0;
  for (let gen = 0; gen < BURN_IN_GENERATIONS; gen++) {
    const currentSize = population.length;
    for (let i = 0; i < BURN_IN_BREEDS_PER_GENERATION; i++) {
      const [a, b] = pickDistinctPairIndices(currentSize, rng);
      const result = breedV2(population[a], population[b], pityCounter, rng);
      if (result.ok) {
        pityCounter = result.nextPityCounter;
        population.push(result.genomeV2);
      }
      // A rejected breed cannot happen here (both parents are always species
      // 1/2), and per contract a rejection would leave pityCounter untouched
      // anyway — nothing to do on the `!result.ok` branch.
    }
  }

  return { population, pityCounter };
}

/**
 * Runs the full Slice 13 calibration simulation end to end (contract
 * §4.5.7): builds the burn-in population, then measures EXACTLY
 * `measuredCount` successful `breedV2` results drawn from it, counting each
 * of the six Gate 1 rarity tiers. Pure function of `seed` — no wall-clock, no
 * hidden state, safe to call repeatedly and compare byte-for-byte.
 */
export function runRarityCalibrationSimulationV2(
  seed: number = RARITY_CALIBRATION_SEED,
  measuredCount: number = RARITY_CALIBRATION_MEASURED_COUNT
): RarityCalibrationResult {
  const rng = mulberry32(seed);
  const { population, pityCounter: pityAfterBurnIn } = buildRepresentativePopulationV2(rng);

  const counts = emptyCounts();
  let pityCounter = pityAfterBurnIn;
  let measured = 0;
  while (measured < measuredCount) {
    const [a, b] = pickDistinctPairIndices(population.length, rng);
    const result = breedV2(population[a], population[b], pityCounter, rng);
    if (!result.ok) continue; // Cannot happen for a species-1/2-only population; defensive only.
    pityCounter = result.nextPityCounter;
    counts[result.rarity] += 1;
    measured += 1;
  }

  return { counts, total: measured, populationSize: population.length, finalPityCounter: pityCounter };
}
